version: "3.9"

services:
  web:
    container_name: chat
    build:
      context: .
      dockerfile: python.Dockerfile
    restart: always
    ports:
      - '8001:8001'
    env_file:
      - .env.example
    command: /python-entrypoint.sh
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis

  redis:
    container_name: redis
    restart: always
    image: redis:5
    env_file:
      - .env.example
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  media:
  static:
